/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Chaity
 */
public class deductions extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
    
    
    
    /**
     * Creates new form deductions
     */
    public deductions() {
        initComponents();
        
        conn =db.java_db();
        //to get it in middle
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2 - getHeight()/2);
        
        lbl_emp.setText(String.valueOf(Emp.empId).toString());
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_design = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_job = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        c_percentage = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        txt_percentage = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_deduction = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbl_total = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_sal = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txt_reason = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lbl_emp = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        c_amount = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Deduction-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Employee ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 30);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(130, 70, 600, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Employee id:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 90, 30);
        jPanel1.add(txt_id);
        txt_id.setBounds(130, 130, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 190, 80, 30);
        jPanel1.add(txt_firstname);
        txt_firstname.setBounds(130, 190, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Surname:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 260, 70, 30);
        jPanel1.add(txt_surname);
        txt_surname.setBounds(130, 260, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date of Birth:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 330, 90, 30);
        jPanel1.add(txt_dob);
        txt_dob.setBounds(130, 330, 170, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Department:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 270, 90, 30);
        jPanel1.add(txt_dep);
        txt_dep.setBounds(460, 260, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Designation:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 134, 80, 30);
        jPanel1.add(txt_design);
        txt_design.setBounds(460, 130, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Status:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 194, 60, 30);
        jPanel1.add(txt_status);
        txt_status.setBounds(460, 190, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Date Hired:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(660, 120, 90, 30);
        jPanel1.add(txt_doj);
        txt_doj.setBounds(790, 120, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Job Title:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(660, 190, 90, 30);
        jPanel1.add(txt_job);
        txt_job.setBounds(780, 190, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Basic Salary:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(660, 260, 100, 30);
        jPanel1.add(txt_salary);
        txt_salary.setBounds(780, 260, 160, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Update Salary by:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 394, 140, 30);

        c_percentage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c_percentage.setText("Percentage(%)");
        c_percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_percentageActionPerformed(evt);
            }
        });
        jPanel1.add(c_percentage);
        c_percentage.setBounds(110, 433, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Percentage:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 490, 90, 30);
        jPanel1.add(txt_percentage);
        txt_percentage.setBounds(130, 490, 140, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Amount:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(290, 490, 70, 30);

        txt_deduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_deductionActionPerformed(evt);
            }
        });
        jPanel1.add(txt_deduction);
        txt_deduction.setBounds(370, 490, 140, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("Total Deduction:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(600, 360, 140, 40);

        lbl_total.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_total.setText("0.00");
        jPanel1.add(lbl_total);
        lbl_total.setBounds(780, 360, 80, 40);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("Salary After Deduction:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(593, 420, 200, 30);

        lbl_sal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_sal.setText("0.00");
        jPanel1.add(lbl_sal);
        lbl_sal.setBounds(830, 410, 80, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Reason:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(30, 584, 90, 20);
        jPanel1.add(txt_reason);
        txt_reason.setBounds(140, 580, 350, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Save");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(790, 520, 160, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Calculate");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 520, 160, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Clear");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(590, 590, 160, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Back to Main Menu");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(790, 590, 160, 40);

        jLabel22.setText("Logged in As:");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(30, 634, 100, 20);

        lbl_emp.setText("emp");
        jPanel1.add(lbl_emp);
        lbl_emp.setBounds(150, 630, 80, 20);
        jPanel1.add(jLabel21);
        jLabel21.setBounds(-150, 0, 0, 0);

        c_amount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c_amount.setText("Amount");
        c_amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_amountActionPerformed(evt);
            }
        });
        jPanel1.add(c_amount);
        c_amount.setBounds(300, 440, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_deductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_deductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_deductionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //Deduction Calculation is done here....
       
        int salary = Integer.parseInt(txt_salary.getText());
        //c_percentage 's work
        if(c_percentage.isSelected()==true){
        
            int percentage = Integer.parseInt(txt_percentage.getText());
            //Calculation 
            int total_percentage_deduction = salary /100 * percentage;
            String x = String.valueOf(total_percentage_deduction);
            int sal = salary - total_percentage_deduction;
            lbl_total.setText(x);
            lbl_sal.setText(String.valueOf(sal));
            
        }  
         //c_percentage's work end here.....
         if(c_amount.isSelected()==true){
        
            int deduction = Integer.parseInt(txt_deduction.getText());
            //Calculation 
            int total_amount_deduction = salary - deduction;
        
            String s = String.valueOf(total_amount_deduction);
           
             lbl_sal.setText(s);
            lbl_total.setText(String.valueOf(deduction));
            
        }
        
       
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        //Working Principle of search key bar.....
        
        try{
         String sql = "select * from  Staff_information where id = ?";  //Collecting information frm database...
         
         pst = conn.prepareStatement(sql);
         pst.setString(1,txt_search.getText());   //when we are giving then getText() method wrks...
         rs=pst.executeQuery();
         
         String add1 = rs.getString("id");
         txt_id.setText(add1);
        
         String add2 = rs.getString("first_name");
         txt_firstname.setText(add2);               //when we want any information then setText() gives us information...
         
         String add3 = rs.getString("surname");
         txt_surname.setText(add3);

         String add4 = rs.getString("Dob");
         txt_dob.setText(add4);

         String add5 = rs.getString("Department");
         txt_dep.setText(add5);

         String add7 = rs.getString("Salary");
         txt_salary.setText(add7);
         
         String add8 = rs.getString("Status");
         txt_status.setText(add8);

         String add9 = rs.getString("Date_hired");
         txt_doj.setText(add9);


         String add10 = rs.getString("job_title");
         txt_job.setText(add10);
         
         String add17 = rs.getString("Designation");
         txt_design.setText(add17);

        }catch(Exception e){
        
            JOptionPane.showMessageDialog(null, "No Data");
        
        }finally{
        
              try{
              
                  rs.close();
                  pst.close();
              
              }catch(Exception e){
                  
             } 
            
 
        }    
    }//GEN-LAST:event_txt_searchKeyReleased

    private void c_percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_percentageActionPerformed
        // TODO add your handling code here:
        c_percentage.setSelected(true);
        c_amount.setSelected(false);
        
        txt_deduction.setEnabled(false);
         txt_deduction.setText(" ");
        
         txt_percentage.setEnabled(true);
         txt_percentage.setEditable(true);
    }//GEN-LAST:event_c_percentageActionPerformed

    private void c_amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_amountActionPerformed
        // TODO add your handling code here:
        c_amount.setSelected(true);
        c_percentage.setSelected(false);
        
        txt_percentage.setEnabled(false);
         txt_percentage.setText(" ");
        
         txt_deduction.setEnabled(true);
         txt_deduction.setEditable(true);
    }//GEN-LAST:event_c_amountActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Working priciple of save button...
        
        int p= JOptionPane.showConfirmDialog(null,"Are you sure you want to save record?","Save Record",JOptionPane.YES_NO_OPTION);
        
        if(p==0){
             
            String value3=lbl_emp.getText();
            
            try{
            
            
                String sql = "insert into Deductions (emp_id,firstname,surname,salary,deduction_amount,deduction_reason,made_by) values(?,?,?,?,?,?, '"+value3+"')";
            
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_id.getText());
                pst.setString(2, txt_firstname.getText());
                pst.setString(3, txt_surname.getText());
                pst.setString(4, txt_salary.getText());
                pst.setString(5, lbl_total.getText());
                pst.setString(6, txt_reason.getText());
               // pst.setString(1, txt_id.getText());
                
                pst.execute();    //returns boolean value
                JOptionPane.showMessageDialog(null, "Data is saved successfully");
                
                
             }catch(Exception e){
            
           
             JOptionPane.showMessageDialog(null,e);

         }
      finally 
       { 
               try{
               rs.close();
               pst.close();
           } 
       catch(Exception e){
               JOptionPane.showMessageDialog(null,e);
               } 
           }
     
        
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //Delete buttons workss...
        
         txt_id.setText(" ");
        txt_firstname.setText(" ");
         txt_surname.setText(" ");
         txt_dob.setText(" ");
          txt_dep.setText(" ");
           txt_status.setText(" ");
           txt_salary.setText(" ");
           txt_design.setText(" ");
           txt_job.setText(" ");
           txt_doj.setText(" ");
           lbl_total.setText("0.00 ");
           txt_percentage.setText(" ");
           txt_deduction.setText(" ");
           txt_reason.setText(" ");
           txt_search.setText(" ");
           lbl_sal.setText("0.00 ");


    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        MainMenu a =new MainMenu();
        a.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    
    //the searching information ends here.........
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deductions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deductions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c_amount;
    private javax.swing.JCheckBox c_percentage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_emp;
    private javax.swing.JLabel lbl_sal;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTextField txt_deduction;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_percentage;
    private javax.swing.JTextField txt_reason;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    // End of variables declaration//GEN-END:variables
}
