/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

/**
 *
 * @author Chaity
 */
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;

public class search_delete_update_info extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form search_delete_update_info
     */
    public search_delete_update_info() {
        initComponents();
        conn=db.java_db();
        Update_table();
     Toolkit toolkit = getToolkit();
    Dimension size = toolkit.getScreenSize();
    setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);

     txt_id.setText(String.valueOf(Emp.empId).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_dob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_tel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_apt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_pc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_dep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_design = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_job = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_address2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search_Delete_Update Information of Employees");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Search Employee ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("Personal Details:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 370, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Employee ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 80, 40);
        jPanel1.add(txt_id);
        txt_id.setBounds(130, 140, 130, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("First name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 90, 40);
        jPanel1.add(txt_firstname);
        txt_firstname.setBounds(130, 200, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Sur name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 250, 100, 30);

        txt_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_surnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_surname);
        txt_surname.setBounds(130, 250, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date of Birth:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 300, 90, 40);
        jPanel1.add(txt_dob);
        txt_dob.setBounds(130, 310, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Gender:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 370, 70, 40);

        r_male.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r_male.setText("Male");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        jPanel1.add(r_male);
        r_male.setBounds(130, 370, 100, 30);

        r_female.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r_female.setText("Female");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(r_female);
        r_female.setBounds(130, 420, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 500, 60, 30);

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_email);
        txt_email.setBounds(410, 500, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Contact:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 490, 60, 40);

        txt_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tel);
        txt_tel.setBounds(120, 490, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Apt/House No:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(280, 150, 110, 30);
        jPanel1.add(txt_apt);
        txt_apt.setBounds(410, 150, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Post Code:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 200, 90, 30);
        jPanel1.add(txt_pc);
        txt_pc.setBounds(410, 200, 170, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Department:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 260, 90, 30);
        jPanel1.add(txt_dep);
        txt_dep.setBounds(410, 260, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Designation:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 320, 80, 30);
        jPanel1.add(txt_design);
        txt_design.setBounds(410, 320, 170, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Status:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(310, 380, 70, 30);
        jPanel1.add(txt_status);
        txt_status.setBounds(410, 380, 170, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Date Hired:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(305, 444, 80, 30);
        jPanel1.add(txt_doj);
        txt_doj.setBounds(410, 440, 170, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Job Title:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(20, 620, 80, 40);

        txt_job.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jobActionPerformed(evt);
            }
        });
        jPanel1.add(txt_job);
        txt_job.setBounds(120, 620, 150, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Basic Salary:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(310, 620, 90, 30);
        jPanel1.add(txt_salary);
        txt_salary.setBounds(410, 620, 170, 30);

        jDesktopPane2.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jDesktopPane2);
        jDesktopPane2.setBounds(660, 40, 270, 300);

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search);
        txt_search.setBounds(180, 80, 400, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Address 1:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(20, 560, 80, 30);

        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        jPanel1.add(txt_address);
        txt_address.setBounds(120, 560, 150, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Address 2:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(310, 560, 90, 30);

        txt_address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_address2ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_address2);
        txt_address2.setBounds(410, 560, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/delete_16x16.gif"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(810, 480, 130, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/update icon.png"))); // NOI18N
        jButton2.setText("Update Record");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(620, 480, 150, 50);

        jLabel21.setText("Employee's picture");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(750, 360, 170, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Back to MainMenu");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(670, 560, 220, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/search pic 2.png"))); // NOI18N
        jPanel1.add(jLabel19);
        jLabel19.setBounds(0, -20, 970, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_table(){
        try{
            String sql ="select * from Staff_information";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
        
        }catch(Exception e){
           
            
            JOptionPane.showMessageDialog(null, e);
        
        
        }finally{
            try{
                 rs.close();
                 pst.close();
            
            
            }catch(Exception e)
            {
            
            
            
            }
        
        }
    
     }
    
    
    
    
    
    
    
    
    
    
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
        try{ 
            String sql ="select * from Staff_information where id=? ";
        pst=conn.prepareStatement(sql);
        pst.setString(1,txt_search.getText());
        rs=pst.executeQuery();
        
        String add1 =rs.getString("id");
        txt_id.setText(add1); 
        
        String add2 =rs.getString("first_name");
        txt_firstname.setText(add2);
        
        String add3 =rs.getString("surname");
        txt_surname.setText(add3);
        
        String add4 =rs.getString("Dob");
        txt_dob.setText(add4);
        
        String add5 =rs.getString("Email");
        txt_email.setText(add5);
        
        String add6 =rs.getString("Telephone");
        txt_tel.setText(add6);
        
        String add7 =rs.getString("Address");
        txt_address.setText(add7);
        
        String add8 =rs.getString("Department");
        txt_dep.setText(add8);
        
        String add10 =rs.getString("Salary");
        txt_salary.setText(add10); 
        
        String add11 =rs.getString("Address2");
        txt_address2.setText(add11);
        
        String add12 =rs.getString("Apartment");
        txt_apt.setText(add12);
        
        String add13 =rs.getString("Post_code");
        txt_pc.setText(add13);
        
        String add14 =rs.getString("Status");
        txt_status.setText(add14);
        
        String add15 =rs.getString("Date_hired");
        txt_doj.setText(add15); 
        
        String add16 =rs.getString("job_title");
        txt_job.setText(add16);
        
        String add17 =rs.getString("Designation");
        txt_design.setText(add17);
        
        byte[] image = rs.getBytes("Image"); 
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(image).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH)); 
        img.setIcon(imageIcon);
        
         pst.execute(); 

        }
        catch(Exception e){ 
        } 
        finally 
        { 
            try{ 
                rs.close(); 
                pst.close();
            } 
            catch(Exception e){
            } 
        }
        
        
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {     
         try{ 
             
         String sql ="delete from Staff_information where id=? ";
         pst=conn.prepareStatement(sql);
         pst.setString(1, txt_id.getText());
         pst.execute(); 
         JOptionPane.showMessageDialog(null,"Record Deleted"); 
         }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
         }finally { 
             try{ 
                 rs.close(); pst.close();
             } catch(Exception e){
             }
         }
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update record?","Update Record",JOptionPane.YES_NO_OPTION);
        if(x==0)
        {     
        try{
        
            String val = txt_firstname.getText();
            String val2 = txt_surname.getText();
            String val3 = txt_dob.getText();
            String val4 = txt_id.getText();
            String val5 = txt_email.getText();
            String val6 = txt_tel.getText();
            String val7 = txt_address.getText();
            String val8 = txt_dep.getText();
            String val9 = txt_address2.getText();
            String val10 = txt_apt.getText();
            String val11 = txt_pc.getText();
            String val12 = txt_design.getText();
            String val13 = txt_status.getText();
            String val14 = txt_salary.getText();
            String val15 = txt_job.getText();
            String val16 = txt_doj.getText();
           // String val17 = jradioButton1.getText();
            
            String sql = "update Staff_information set id = '"+val4+"',first_name = '"+val+"',surname = '"+val2+"',"
                   +" dob = '"+val3+"',Email = '"+val5+"',Telephone = '"+val6+"',"
                    +"Address = '"+val9+"',Department = '"+val8+"',Address2 = '"+val9+"',"
                    +"Apartment = '"+val10+"',Post_code = '"+val11+"',Designation = '"+val12+"',"
                    +"Status = '"+val13+"',Salary = '"+val14+"',job_title = '"+val15+"',"
                    +"Date_Hired = '"+val16+"'  where id = '"+val4+"'    ";
                    
            
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            
            
            JOptionPane.showMessageDialog(null, "Record Updated!");

            
            
            
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }finally
        {
           try{
           }catch(Exception e){
           
           
           }
        }
        }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_jobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jobActionPerformed

    private void txt_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telActionPerformed

    private void txt_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_surnameActionPerformed

    private void txt_address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_address2ActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        
         gender = "Female";
        r_female.setSelected(true);
        r_male.setSelected(false);
        
    }//GEN-LAST:event_r_femaleActionPerformed

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:
         gender = "Male";
        r_male.setSelected(true);
        r_female.setSelected(false);
        

        
        
        
    }//GEN-LAST:event_r_maleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        MainMenu mmone = new MainMenu();
        mmone.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_delete_update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_delete_update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_delete_update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_delete_update_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search_delete_update_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_address2;
    private javax.swing.JTextField txt_apt;
    private javax.swing.JTextField txt_dep;
    private javax.swing.JTextField txt_design;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_job;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
    private String gender;
}
